# -*- coding: utf-8 -*-
# !/usr/bin/env python3
import Const

Const.INDEX_OF_INTERNET_ID = 0
Const.INDEX_OF_THREAD_NAME = 1
Const.INDEX_OF_IDENTD = 2
Const.INDEX_OF_USER_ID = 3
Const.INDEX_OF_DATETIME_IN_LOG = 4
Const.INDEX_OF_REST_METHOD = 5
Const.INDEX_OF_REST_API = 6
Const.INDEX_OF_HTTP_VERSION = 7
Const.INDEX_OF_STATUS_NUMBER = 8
Const.INDEX_OF_PACKET_SIZE = 9
Const.INDEX_OF_BASE_URL = 10
Const.INDEX_OF_USER_AGENT = 11
Const.INDEX_OF_USER_AGENT_IF_NOT_EXIST = 12
Const.INDEX_OF_RESPONSE_TIME = 13

